// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package proc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEventHdr struct {
	_           structs.HostLayout
	Pid         uint32
	Ppid        uint32
	Kind        uint32
	Nargs       uint32
	TsNs        int64
	ExitCode    int32
	HasExitCode uint8
	IsToplevel  uint8
	_           [2]byte
	FilenameLen uint32
	ArgsSize    uint32
}

type bpfExecScratch struct {
	_        structs.HostLayout
	Hdr      bpfEventHdr
	Filename [256]int8
	Args     [16384]int8
}

type bpfProcInfo struct {
	_          structs.HostLayout
	IsShell    uint8
	IsToplevel uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapConfigMap        = "config_map"
	bpfMapDropCount        = "drop_count"
	bpfMapEvents           = "events"
	bpfMapExecs            = "execs"
	bpfMapHeap             = "heap"
	bpfMapRootPidMap       = "root_pid_map"
	bpfMapStateLostCount   = "state_lost_count"
	bpfMapTrackedPids      = "tracked_pids"
	bpfMapUntrackedCount   = "untracked_count"
	bpfProgHandleExecve    = "handle_execve"
	bpfProgHandleExit      = "handle_exit"
	bpfProgHandleExitGroup = "handle_exit_group"
	bpfProgHandleFork      = "handle_fork"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleExecve    *ebpf.ProgramSpec `ebpf:"handle_execve"`
	HandleExit      *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleExitGroup *ebpf.ProgramSpec `ebpf:"handle_exit_group"`
	HandleFork      *ebpf.ProgramSpec `ebpf:"handle_fork"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ConfigMap      *ebpf.MapSpec `ebpf:"config_map"`
	DropCount      *ebpf.MapSpec `ebpf:"drop_count"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	Execs          *ebpf.MapSpec `ebpf:"execs"`
	Heap           *ebpf.MapSpec `ebpf:"heap"`
	RootPidMap     *ebpf.MapSpec `ebpf:"root_pid_map"`
	StateLostCount *ebpf.MapSpec `ebpf:"state_lost_count"`
	TrackedPids    *ebpf.MapSpec `ebpf:"tracked_pids"`
	UntrackedCount *ebpf.MapSpec `ebpf:"untracked_count"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ConfigMap      *ebpf.Map `ebpf:"config_map"`
	DropCount      *ebpf.Map `ebpf:"drop_count"`
	Events         *ebpf.Map `ebpf:"events"`
	Execs          *ebpf.Map `ebpf:"execs"`
	Heap           *ebpf.Map `ebpf:"heap"`
	RootPidMap     *ebpf.Map `ebpf:"root_pid_map"`
	StateLostCount *ebpf.Map `ebpf:"state_lost_count"`
	TrackedPids    *ebpf.Map `ebpf:"tracked_pids"`
	UntrackedCount *ebpf.Map `ebpf:"untracked_count"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ConfigMap,
		m.DropCount,
		m.Events,
		m.Execs,
		m.Heap,
		m.RootPidMap,
		m.StateLostCount,
		m.TrackedPids,
		m.UntrackedCount,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleExecve    *ebpf.Program `ebpf:"handle_execve"`
	HandleExit      *ebpf.Program `ebpf:"handle_exit"`
	HandleExitGroup *ebpf.Program `ebpf:"handle_exit_group"`
	HandleFork      *ebpf.Program `ebpf:"handle_fork"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleExecve,
		p.HandleExit,
		p.HandleExitGroup,
		p.HandleFork,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
