// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package net

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfConnKey struct {
	_    structs.HostLayout
	Tgid uint32
	Fd   uint32
}

type bpfConnState struct {
	_             structs.HostLayout
	Family        uint8
	Addr          [16]uint8
	_             [1]byte
	Port          uint16
	HelloCaptured uint8
	_             [3]byte
	OpenTsNs      uint64
}

type bpfNetEvent struct {
	_       structs.HostLayout
	Hdr     bpfNetEventHdr
	Payload [1024]uint8
}

type bpfNetEventHdr struct {
	_          structs.HostLayout
	Type       uint8
	Family     uint8
	Port       uint16
	Tgid       uint32
	Tid        uint32
	Fd         uint32
	TsNs       uint64
	Addr       [16]uint8
	Seq        uint64
	PayloadLen uint32
	_          [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapConns         = "conns"
	bpfMapDropCount     = "drop_count"
	bpfMapHeap          = "heap"
	bpfMapNetEvents     = "net_events"
	bpfMapTrackedPids   = "tracked_pids"
	bpfProgHandleExit   = "handle_exit"
	bpfProgHandleFork   = "handle_fork"
	bpfProgTraceClose   = "trace_close"
	bpfProgTraceConnect = "trace_connect"
	bpfProgTraceSendmsg = "trace_sendmsg"
	bpfProgTraceSendto  = "trace_sendto"
	bpfProgTraceWrite   = "trace_write"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleExit   *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFork   *ebpf.ProgramSpec `ebpf:"handle_fork"`
	TraceClose   *ebpf.ProgramSpec `ebpf:"trace_close"`
	TraceConnect *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceSendmsg *ebpf.ProgramSpec `ebpf:"trace_sendmsg"`
	TraceSendto  *ebpf.ProgramSpec `ebpf:"trace_sendto"`
	TraceWrite   *ebpf.ProgramSpec `ebpf:"trace_write"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Conns       *ebpf.MapSpec `ebpf:"conns"`
	DropCount   *ebpf.MapSpec `ebpf:"drop_count"`
	Heap        *ebpf.MapSpec `ebpf:"heap"`
	NetEvents   *ebpf.MapSpec `ebpf:"net_events"`
	TrackedPids *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Conns       *ebpf.Map `ebpf:"conns"`
	DropCount   *ebpf.Map `ebpf:"drop_count"`
	Heap        *ebpf.Map `ebpf:"heap"`
	NetEvents   *ebpf.Map `ebpf:"net_events"`
	TrackedPids *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Conns,
		m.DropCount,
		m.Heap,
		m.NetEvents,
		m.TrackedPids,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleExit   *ebpf.Program `ebpf:"handle_exit"`
	HandleFork   *ebpf.Program `ebpf:"handle_fork"`
	TraceClose   *ebpf.Program `ebpf:"trace_close"`
	TraceConnect *ebpf.Program `ebpf:"trace_connect"`
	TraceSendmsg *ebpf.Program `ebpf:"trace_sendmsg"`
	TraceSendto  *ebpf.Program `ebpf:"trace_sendto"`
	TraceWrite   *ebpf.Program `ebpf:"trace_write"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleExit,
		p.HandleFork,
		p.TraceClose,
		p.TraceConnect,
		p.TraceSendmsg,
		p.TraceSendto,
		p.TraceWrite,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
