// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package net

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tlsbpfSslFrame struct {
	_       structs.HostLayout
	Hdr     tlsbpfSslFrameHdr
	Payload [16384]uint8
}

type tlsbpfSslFrameHdr struct {
	_    structs.HostLayout
	Tgid uint32
	Tid  uint32
	TsNs uint64
	Len  uint32
	_    [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tlsbpfMapDropCount      = "drop_count"
	tlsbpfMapFaultedReads   = "faulted_reads"
	tlsbpfMapSslEvents      = "ssl_events"
	tlsbpfMapSslHeap        = "ssl_heap"
	tlsbpfMapTrackedPids    = "tracked_pids"
	tlsbpfProgHandleExit    = "handle_exit"
	tlsbpfProgHandleFork    = "handle_fork"
	tlsbpfProgProbeSslWrite = "probe_ssl_write"
)

// loadTlsbpf returns the embedded CollectionSpec for tlsbpf.
func loadTlsbpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsbpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tlsbpf: %w", err)
	}

	return spec, err
}

// loadTlsbpfObjects loads tlsbpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlsbpfObjects
//	*tlsbpfPrograms
//	*tlsbpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlsbpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTlsbpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlsbpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsbpfSpecs struct {
	tlsbpfProgramSpecs
	tlsbpfMapSpecs
	tlsbpfVariableSpecs
}

// tlsbpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsbpfProgramSpecs struct {
	HandleExit    *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFork    *ebpf.ProgramSpec `ebpf:"handle_fork"`
	ProbeSslWrite *ebpf.ProgramSpec `ebpf:"probe_ssl_write"`
}

// tlsbpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsbpfMapSpecs struct {
	DropCount    *ebpf.MapSpec `ebpf:"drop_count"`
	FaultedReads *ebpf.MapSpec `ebpf:"faulted_reads"`
	SslEvents    *ebpf.MapSpec `ebpf:"ssl_events"`
	SslHeap      *ebpf.MapSpec `ebpf:"ssl_heap"`
	TrackedPids  *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// tlsbpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsbpfVariableSpecs struct {
}

// tlsbpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlsbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsbpfObjects struct {
	tlsbpfPrograms
	tlsbpfMaps
	tlsbpfVariables
}

func (o *tlsbpfObjects) Close() error {
	return _TlsbpfClose(
		&o.tlsbpfPrograms,
		&o.tlsbpfMaps,
	)
}

// tlsbpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlsbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsbpfMaps struct {
	DropCount    *ebpf.Map `ebpf:"drop_count"`
	FaultedReads *ebpf.Map `ebpf:"faulted_reads"`
	SslEvents    *ebpf.Map `ebpf:"ssl_events"`
	SslHeap      *ebpf.Map `ebpf:"ssl_heap"`
	TrackedPids  *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *tlsbpfMaps) Close() error {
	return _TlsbpfClose(
		m.DropCount,
		m.FaultedReads,
		m.SslEvents,
		m.SslHeap,
		m.TrackedPids,
	)
}

// tlsbpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTlsbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsbpfVariables struct {
}

// tlsbpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlsbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsbpfPrograms struct {
	HandleExit    *ebpf.Program `ebpf:"handle_exit"`
	HandleFork    *ebpf.Program `ebpf:"handle_fork"`
	ProbeSslWrite *ebpf.Program `ebpf:"probe_ssl_write"`
}

func (p *tlsbpfPrograms) Close() error {
	return _TlsbpfClose(
		p.HandleExit,
		p.HandleFork,
		p.ProbeSslWrite,
	)
}

func _TlsbpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tlsbpf_bpfeb.o
var _TlsbpfBytes []byte
